#!/usr/bin/env python3
"""
protoc plugin: generates coap_pp::NanopbFields<T> specializations for nanopb messages.

Usage (invoked automatically by protoc via CMake):
  protoc --plugin=protoc-gen-coap_pp_fields=<path>/protoc-gen-coap_pp_fields \
         --coap_pp_fields_out=<output_dir> \
         -I<proto_dir> foo.proto

Generates <output_dir>/foo.coap_pp_fields.hpp containing one specialization per
message type defined in foo.proto.
"""

import sys
from google.protobuf.compiler import plugin_pb2 as plugin


def nanopb_type_name(msg, parent=""):
    """
    Build the nanopb C struct name for a message descriptor.

    nanopb flattens nested messages: Outer.Inner -> Outer_Inner.
    Package names become a leading prefix: package foo.bar -> foo_bar_MsgName.
    """
    return f"{parent}_{msg.name}" if parent else msg.name


def collect_messages(message_types, parent=""):
    """Yield nanopb C struct names for all messages (recursive over nested types)."""
    for msg in message_types:
        name = nanopb_type_name(msg, parent)
        yield name
        yield from collect_messages(msg.nested_type, name)


def nanopb_package_prefix(package):
    """Convert a proto package name to the nanopb C prefix (dots become underscores)."""
    if not package:
        return ""
    return package.replace(".", "_")


def generate_fields_header(proto_file):
    base = proto_file.name
    if base.endswith(".proto"):
        base = base[: -len(".proto")]

    # Strip any leading path components so the include only uses the basename.
    # (The generated .pb.h lives in the same build directory.)
    bare_base = base.split("/")[-1]

    pb_header = f"{bare_base}.pb.h"
    output_name = f"{bare_base}.coap_pp_fields.hpp"

    pkg_prefix = nanopb_package_prefix(proto_file.package)
    messages = list(collect_messages(proto_file.message_type, pkg_prefix))
    if not messages:
        return None, None

    pkg_upper = pkg_prefix.upper()
    base_upper = bare_base.upper()
    guard = f"PB_{pkg_upper + '_' if pkg_upper else ''}{base_upper}_COAP_PP_FIELDS_HPP_INCLUDED"

    lines = [
        "// Auto-generated by protoc-gen-coap_pp_fields. Do not edit.",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <cstddef>",
        "",
        f'#include "{pb_header}"',
        '#include <coap_pp_serde_nanopb/deserializer.hpp>',
        "",
    ]

    for name in messages:
        lines += [
            "template <>",
            f"struct coap_pp::NanopbFields<{name}> {{",
            f"  static constexpr const pb_msgdesc_t* kFields = {name}_fields;",
            f"  static constexpr std::size_t kMaxEncodedSize = {name}_size;",
            "};",
            "",
        ]

    lines += [f"#endif /* {guard} */"]

    return output_name, "\n".join(lines)


def main():
    request = plugin.CodeGeneratorRequest()
    request.ParseFromString(sys.stdin.buffer.read())

    response = plugin.CodeGeneratorResponse()
    response.supported_features = (
        plugin.CodeGeneratorResponse.FEATURE_PROTO3_OPTIONAL
    )

    files_to_generate = set(request.file_to_generate)
    for proto_file in request.proto_file:
        if proto_file.name not in files_to_generate:
            continue
        output_name, content = generate_fields_header(proto_file)
        if output_name:
            f = response.file.add()
            f.name = output_name
            f.content = content

    sys.stdout.buffer.write(response.SerializeToString())


if __name__ == "__main__":
    main()
